# https://docs.opendevshop.com/using-devshop/deployment-hooks
# Fires after an environment is installed.
install: |



# Fires after code is deployed. A "deployment" happens when you push to your
# git repository or select a new branch or tag for your environment.
deploy: |
  echo "Running hooks in the $DEVSHOP_ENVIRONMENT environment for the $DEVSHOP_PROJECT..."
  npm install --prefix web/themes/custom/ppd
  drush  {{alias}}  cache-rebuild -y
  drush  {{alias}}  updatedb -y
  env
